import { Header } from "./_layout/Header";
import "./globals.css";
import "./custom.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Footer } from "./_layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-white text-gray-900">
        <div className="relative min-h-screen">
          <ToastContainer
            position="top-right"
            autoClose={500}
            hideProgressBar={false}
            closeButton={false}
            theme="colored"
            className="z-[9999]"
            toastClassName="rounded-lg shadow-md text-sm"
            bodyClassName="p-3"
          />

          <Header />
          <main className="">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
